<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RhubarbGeekNz.AppleScript</AssemblyName>
    <Copyright>Copyright © 2026 Roger Brown</Copyright>
    <Version>1.0.1</Version>
    <AssemblyTitle>PowerShell AppleScript Cmdlet</AssemblyTitle>
    <Product>AppleScript for PowerShell</Product>
    <Company>rhubarb-geek-nz</Company>
    <PackageId>rhubarb-geek-nz.AppleScript</PackageId>
    <Title>AppleScript Cmdlet for PowerShell</Title>
    <Description>This uses NSAppleScript to perform the execution within the PowerShell process. No native binary or support application is used. Handlers within scripts can be invoked by name and passed a list of arguments. Translation is performed between the common NSAppleEventDescriptor types and PowerShell objects. Scripts can be passed directly as strings or by path to the file.</Description>
    <Authors>Roger Brown</Authors>
    <PackageProjectUrl>https://github.com/rhubarb-geek-nz/AppleScript</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rhubarb-geek-nz/AppleScript.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>AppleScript</PackageTags>
    <CertificateThumbprint>601A8B683F791E51F647D34AD102C38DA4DDB65F</CertificateThumbprint>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="Sign" AfterTargets="Compile" Condition=" '$(Configuration)' == 'Release' AND '$(OS)' == 'Windows_NT' ">
    <ItemGroup>
        <FileToSign Include="$(IntermediateOutputPath)$(TargetFileName)" />
    </ItemGroup>
    <Message Importance="high" Text="Signing assemblies: @(FileToSign)" />
    <SignFile SigningTarget="@(FileToSign)" CertificateThumbprint="$(CertificateThumbprint)" TimestampUrl="http://timestamp.digicert.com" />
  </Target>

  <Target Name="Package" AfterTargets="Publish" Condition=" '$(Configuration)' == 'Release' ">
    <ItemGroup>
      <FilesToDelete Include="$(PublishDir)*.deps.json" />
      <FilesToDelete Include="$(PublishDir)*.pdb" />
      <FilesToDelete Include="$(PublishDir)ref\**" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
    <Exec Command="pwsh -ExecutionPolicy Bypass -NoProfile -File ./package.ps1 $(ProjectName) $(IntermediateOutputPath) $(OutDir) $(PublishDir) $(Version)" />
    <RemoveDir Directories="$(PublishDir)runtimes;$(PublishDir)ref" />
    <Delete Files="$(OutDir)$(PackageId).psd1" />
  </Target>

</Project>
